### ISSUE TITLE
How can we share an Image/Video from URL directly

### ISSUE THREAD

**Issue by lakshaylbb** [WICG/web-share#104]
If it is not possible from URL, is there any method to convert a URL of image/video to a filelist object?

**Comment by ewilligers** [comment]
XMLHttpRequest can be used to request the contents, but many sites use CORS to prevent the contents from being made available to other sites.

**Comment by lakshaylbb** [comment]
Thanks Eric. I've setup a pen for this.

 https://codepen.io/lakshaylbb/pen/gNoaLz?editors=1010

Hope this helps other developers
