### ISSUE TITLE
why "optional" in share(optional ShareData data)?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/web-share#109]
Given that the first thing we need to check is if `data` has some members, shouldn't the share() signature actually make `data` required? 

Alternatively, the method signature should default to the empty dictionary: 

```
[SecureContext] Promise<void> share(optional ShareData data = {});
```

However, I think we should just make `data` required.

**Comment by ewilligers** [comment]
See the first note in https://wicg.github.io/web-share/level-2/#navigator-interface

> The data argument is marked as "optional", but it is effectively required; share() will return a rejected promise with a TypeError if called with no arguments. WebIDL mandates that it be optional because the dictionary members are all optional. See WebIDL Issue #130.

https://heycam.github.io/webidl/#idl-operations

> If the type of an argument is a dictionary type or a union type that has a dictionary type as one of its flattened member types, and that dictionary type and its ancestors have no required members, and the argument is either the final argument or is followed only by optional arguments, then the argument must be specified as optional and have a default value provided.

We should add `= {}`
