### ISSUE TITLE
demo code fails to parse in some browsers

### ISSUE THREAD

**Issue by drewbenn** [WICG/web-share#14]
The demo code fails to _**parse**_ in some browsers, leading the _entire_ javascript file to be rejected. Specifically, at [https://developers.google.com/web/updates/2016/10/navigator-share](https://developers.google.com/web/updates/2016/10/navigator-share), the phrase:

`.then(() => console.log('Successful share'))
.catch(error => console.log('Error sharing:', error))`

Similar code is also used in `demos/share.html` and also fails to parse.

It fails in Konqueror 4.14.2 (Debian stable (Jessie 8)). I believe (based on access logs for users who reported problems) it also fails in:

"Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

"Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G35 Safari/601.1"

**Comment by mgiuca** [comment]
@paulkinlan FYI

I'm inclined to keep it this way since it's good modern JavaScript style and is [supported on all modern browsers](https://caniuse.com/#feat=arrow-functions).
