### ISSUE TITLE
A little idea maybe useful or not?

### ISSUE THREAD

**Issue by ayumihamsaki** [WICG/web-share#15]
Why not add a rel-share to this spec.?

See here: http://microformats.org/wiki/sharelink-examples

So we end up with this:

`<a role="link" rel="share" href="https://www.example.com/share?title={title}&text={text}&url={url}">Share This</a>`

An update to Approach 1 found here: https://github.com/WICG/web-share-target/blob/master/docs/interface.md#approach-1-1

Just an idea?

**Comment by delapuente** [comment]
Sorry, I don't understand what you mean. Are you referring to add some kind of declarative/pure HTML way to trigger a share?

**Comment by mgiuca** [comment]
I'm not really sure what this means either, but it seems to be relevant to Web Share Target, not Web Share. Please file a bug [here](https://github.com/WICG/web-share-target/issues/) if that's what you mean.
