### ISSUE TITLE
Feedback: sharing an image via Data URI resulted in user gesture error

### ISSUE THREAD

**Issue by owencm** [WICG/web-share#16]
The following feedback was emailed to me so passing on here:

> I'm actually working on a collaborative whiteboard application. I wanted to share the drawings on the canvas as an image. I generated the image and tried to share it using such a code:
> 
> let url = canvasElement.toDataURL('image/png');
> 
> navigator.share({
>   title: document.title,
>   text: "Shared whiteboard",
>   url: url
> }).then(() => console.log('Successful share'))
> .catch(error => console.log('Error sharing:', error));
> 
> However, I got an exception:
> "Error sharing: DOMException: Must be handling a user gesture to perform a share request."
> 
> I would say this was quite unexpected, because I was clicking on a button in the same way as with the sharing of a regular URL. I'm not sure why this user gesture was not accepted.
> Moreover, is sharing of images in such a way supported?

**Comment by mgiuca** [comment]
Closing since this is a Chrome implementation bug. (Pasted into https://crbug.com/704447)
