### ISSUE TITLE
Feature request: Add April Fools protection

### ISSUE THREAD

**Issue by mgiuca** [WICG/web-share#18]
If `navigator.share` is used on a web page that was written on April 1, the User Agent should display a warning to the user, with this text or similar:

"Warning: You are sharing content that may contain false information or fake news. Are you sure you want to spread this content?"

**Comment by joeblew99** [comment]
:)

**Comment by mgiuca** [comment]
I think it will be technically infeasible to determine whether an article was written on April 1, so WontFix.
