### ISSUE TITLE
Require user gesture?

### ISSUE THREAD

**Issue by foolip** [WICG/web-share#21]
Presumably `navigator.share(...)` will show some modal UI. Should this be gated behind a user gesture, or are there use cases where the user isn't interacting with the page and would still be able to understand why a share UI is being presented?

A consequence of requiring a user gesture would be that the API couldn't be exposed in workers.

**Comment by mgiuca** [comment]
Whoa, GitHub automatically closes a bug if you merge a pull request that says "Fixes X". #til

Thanks for the suggestion. We already require user gesture in the Chrome implementation. I just added this note to the interface document.

**Comment by foolip** [comment]
How does this work in workers? The Chromium implementation doesn't have it in workers yet, should that be removed from the proto-spec as well?

**Comment by mgiuca** [comment]
I'm not trying to do too much work on the proto spec (since I'm working on the *real* spec). I'm not sure... I think the spec should contain what we want it to do, not merely what it currently does in Chrome. And I think it should work in workers.

https://crbug.com/660020

**Comment by foolip** [comment]
OK, so there is a notion of user gestures in workers too. The requirement of having a notificationclick event sounds like it should perhaps be part of https://html.spec.whatwg.org/#triggered-by-user-activation or a similar workers-only definition.

Although, if it's just that event, then just keeping it in this spec should be fine for now.

**Comment by foolip** [comment]
BTW, where is the *real* spec?

**Comment by kael** [comment]
Have you considered the case of temporary shared private server-side generated URLs ?

I was to implement temporary shared URLs combined with the [nginx ` secure_link_md5` directive](https://www.nginx.com/blog/securing-urls-secure-link-module-nginx-plus/) which generates links like `/files/pricelist.html?md5=AUEnXC7T-Tfv9WLsWbf-mw&expires=1483228740`, but stumbled upon `error: DOMException: Must be handling a user gesture to perform a share request.`

In my case, the user would click on the "share" button, an HTTP request would be made to fetch a temporary URL (Oauth, Ticket based, etc) and the result URL passed to the `navigator.share`.

The alternative for now it to generate the token on client side, which would expose the _"shared token"_ used for the ticket generation (in the nginx case), and could trigger heavy computation.

Could there be a way to pass `navigator.share` as a callback, or for `navigator.share` to take a promise (like an HTTP or WS request/response) which result would be passed as the parameters to be then called ?

**Comment by mgiuca** [comment]
@kael: This is actually a Chrome bug (the standard should allow a user gesture token to propagate through a fetch). We've had this issue come up internally. https://crbug.com/760848 tracks the Chrome bug. Status is blocked on a major refactor (since this is a bug in the user gesture system itself, not Web Share).

There is a rather horrible, but functional workaround posted in https://crbug.com/760848#c7. See makePromisePropagateUserGesture in the linked .html file.

**Comment by kael** [comment]
@mgiuca: Thanks for the precisions.

I actually used a two-steps process, with a second modal popping up once the server has replied with the generated temporary URI, and it's actually quite fast over WebSocket, and acceptable on the UX point-of-view.

Anyway, I'll track the tickets. Cheers.
