### ISSUE TITLE
Consider adding "Web applications as share targets" to the specification

### ISSUE THREAD

**Issue by delapuente** [WICG/web-share#23]
WebShare currently allows developers to share content, but it would also define a mechanism for Web applications to become share targets and so, leverage PWA by closing another gap between native and web apps. It is of particular importance for social web applications.

See https://webperf.ninja/2017/twitter-pwa/

**Comment by mgiuca** [comment]
This is being tracked as a separate specification at the moment: https://github.com/WICG/web-share-target
