### ISSUE TITLE
canShare should be async...

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/web-share#3]
Having something like:

``` JAVA
partial interface Navigator {
  boolean canShare();
};
```

Would probably need to be async. The problems is: 
1. UA checks list of handlers (e.g., at launch time)
2. user deletes app that handles type X (list out of date now).
3. UA says, "sure, you can totally share this"!
4. user has a bad time. 

Otherwise, the UA would need to do IPC to check if there are handlers available - so basically that's a nonstarter there, or am I missing something?

**Comment by mgiuca** [comment]
`canShare` is no longer part of the current proposal.
