### ISSUE TITLE
Editorial: various missing links

### ISSUE THREAD

**Issue by domenic** [WICG/web-share#37]
- URL parser: should go to https://url.spec.whatwg.org/#concept-url-parser (but see #38)
- Triggered by user activation: https://html.spec.whatwg.org/#triggered-by-user-activation
- In parallel: https://html.spec.whatwg.org/#in-parallel
- Valid URL string: https://url.spec.whatwg.org/#valid-url-string
- Promise creation/manipulation should link to https://www.w3.org/2001/tag/doc/promises-guide
- Exceptions should link to Web IDL (and also should use the somewhat-new syntax, e.g. "AbortError" DOMException instead of just AbortError, since there is no type called AbortError).

In Bikeshed, most of this should be a simple matter of e.g. doing `[=in parallel=]` instead of `in parallel`.

**Comment by domenic** [comment]
Oh, I see, this is using ReSpec; that makes things harder. Probably this is lower-priority then given the effort/reward ratio.

**Comment by mgiuca** [comment]
I'm confused, all of those links are already in place, except for promise creation.

Promise creation: should that really link to a guide for spec authors? Isn't there something more authoritative?

**Comment by domenic** [comment]
Oh, weird, this appears to be a Firefox vs. Chrome problem! They are not present in Firefox. Some sort of ReSpec bug maybe? @marcoscaceres?

The promise-using guide is our current best source for normative algorithms on manipulating promises; there is a long-standing TODO to move it into Web IDL or ES, but it hasn't happened yet.

**Comment by mgiuca** [comment]
I don't see the problem in Firefox.

I'll put up a CL that includes linking to promises guide.

**Comment by domenic** [comment]
For the record, tracking the maybe-ReSpec, maybe-my-computer issue at https://github.com/w3c/respec/issues/1285.
