### ISSUE TITLE
Editorial: bibliography links go nowhere

### ISSUE THREAD

**Issue by domenic** [WICG/web-share#41]
E.g. "The Navigator interface is defined in [HTML].", but clicking on the "HTML" link goes nowhere. The bibliography appears to be missing.

This may be related to some kind of broken build process which is also producing some escaped HTML at the top of the document:

```html
<p><a href="https://www.w3.org/" class="logo"> <span id=""> <img alt="W3C" src="https://www.w3.org/StyleSheets/TR/2016/logos/W3C" height="72" width="48"> </span></a></p> 
```

**Comment by mgiuca** [comment]
Seems to be fixed now... the weird shit at the top started showing up a few days ago and is also a ReSpec bug (https://github.com/w3c/respec/issues/1281). Checked in both Chrome and Firefox.

**Comment by domenic** [comment]
I'm still getting problems in Firefox, including in a fresh profile and in Nightly. Console dump:

```
null  respec-w3c-common:1:466302
	<anonymous> https://www.w3.org/Tools/respec/respec-w3c-common:1:466302
UnknownError  respec-w3c-common:1:403380
Plugin core/biblio took too long. Object { name: "core/biblio", done: Promise, resolveRef: e.resolveRef</<(), run: e.run</<(), wireReference: e.wireReference(), stringifyReference: s(), 1 more… }  respec-w3c-common:1:64090
	a/</</a< https://www.w3.org/Tools/respec/respec-w3c-common:1:64090
Error: Plugin core/biblio took too long.
Stack trace:
a/</</a<@https://www.w3.org/Tools/respec/respec-w3c-common:1:64111
  respec-w3c-common:1:64802
	e/< https://www.w3.org/Tools/respec/respec-w3c-common:1:64802
	n https://www.w3.org/Tools/respec/respec-w3c-common:1:29630
	l/< https://www.w3.org/Tools/respec/respec-w3c-common:1:30749
	o/</e[t] https://www.w3.org/Tools/respec/respec-w3c-common:1:29806
	r https://www.w3.org/Tools/respec/respec-w3c-common:1:63748
	r/< https://www.w3.org/Tools/respec/respec-w3c-common:1:63877
Plugin  took too long. Object { run: run() }  respec-w3c-common:1:64090
	a/</</a< https://www.w3.org/Tools/respec/respec-w3c-common:1:64090
Error: Plugin  took too long.
Stack trace:
a/</</a<@https://www.w3.org/Tools/respec/respec-w3c-common:1:64111
  respec-w3c-common:1:64802
	e/< https://www.w3.org/Tools/respec/respec-w3c-common:1:64802
	n https://www.w3.org/Tools/respec/respec-w3c-common:1:29630
	l/< https://www.w3.org/Tools/respec/respec-w3c-common:1:30749
	o/</e[t] https://www.w3.org/Tools/respec/respec-w3c-common:1:29806
	r https://www.w3.org/Tools/respec/respec-w3c-common:1:63748
	r/< https://www.w3.org/Tools/respec/respec-w3c-common:1:63877

````

So weird. I can't imagine what it could be.

I guess it has to be a ReSpec bug, so I'll migrate over to their issue tracker.

**Comment by marcoscaceres** [comment]
Just pushed a patch to do recovery for the IDB issue to ReSpec. It's a gecko bug - and yeah, it seems to happen if you have stuff in your profile. I don't think we (Moz) have managed to work out what is happening yet :( It's been showing up at random for a while, but this is the first time it's affected ReSpec.

**Comment by marcoscaceres** [comment]
(sorry also for the "weird shit" at the top of the doc - although I do like to keep ReSpec a little weird 🤠, please do let me know when things like that happen)

**Comment by mgiuca** [comment]
@marcoscaceres I will do :) (I was going to wait a day to see if it settles before filing bugs.)
