### ISSUE TITLE
Allow for share target addition in target selection step of navigator.share()

### ISSUE THREAD

**Issue by davmillar** [WICG/web-share#52]
In the current spec, [Section 2.1.1 step 5.1](https://wicg.github.io/web-share/#share-method) instructs the browser "If there are no share targets available, reject p with AbortError, and abort these steps."

I'd like to propose instead that step 5.2 be expanded to allow a UI workflow for adding a new share target to use immediately. In the event a browser has no such UI and no share targets exist, only then should the promise automatically be rejected with an AbortError. This change would also negate the verbiage in Section 2.1 that instructs the browser in regards to feature detection when no share targets are available.

**Comment by davmillar** [comment]
Chrome 61 currently implements navigator.share in this manner, which conflicts with the current spec. [I've opened a ticket there](https://bugs.chromium.org/p/chromium/issues/detail?id=764361) as well.

**Comment by mgiuca** [comment]
Hi,

I absolutely agree that the sort of UX you propose is desirable (i.e., being able to dynamically find a share target at the time the picker is shown) and that the spec should allow for it.

However, I would argue that the current spec language does allow this, and that Chrome 61 is not in conflict with the spec (noted https://crbug.com/764361 --- the behaviour is not desirable but it's also not in conflict with the spec).

- §2.1.1.5.1 states "If there are no share targets available, reject p with AbortError, and abort these steps." It doesn't say it has to be done immediately; for example it would be valid to show an error dialog that says "There are no share targets available. <OK>", and when the user presses <OK>, we reject p. Chrome's current behaviour on desktop is analogous to this, except the "error dialog" takes the form of the picker, with 0 targets shown in the list, and only a <Cancel> button. I agree it's a bad user experience, but it's the same from a spec point of view as the previous example.
- The notion of what it means for a share target to be "available" is entirely up to the user agent. §3 uses deliberately vague language to explain what a share target is: "What constitutes a share target is at the discretion of the user agent." There is no requirement that share targets be pre-registered or that they correspond to apps already installed on the device, etc. If a user agent decides to provide UI for discovering and choosing share targets that the user has not explicitly used before, those share targets would be considered "available". Therefore, §2.1.1.5.1 would not apply and the user agent would not be required to reject the promise before asking the user.

So I don't think the spec needs to change to allow this behaviour (in general, specs should not go into the details of the user experience, apart from saying what data is expected to flow into and out of the UI).

**Comment by davmillar** [comment]
@mgiuca thank you for the clarification and taking time to reply. The availability point makes sense when you put it that way, and the comments regarding the experimental flags in Chrome on the issue page there are good to know as well.
