### ISSUE TITLE
Redundant statement

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/web-share#60]
As the spec already declares [SecureContext] in the IDL, this doesn't need to be stated: 

> Due to the capabilities of the API surface, navigator.share is available only in secure contexts (such as https:// schemes).

**Comment by ewilligers** [comment]
This is non-normative explanative text. Various other specifications using [SecureContext] have similar explanative text in their Security chapters. Examples:


[Service Workers](https://w3c.github.io/ServiceWorker/#security-considerations)
> Service workers must execute in secure contexts. Service worker clients must also be secure contexts to register a service worker registration, to get access to the service worker registrations and the service workers, to do messaging with the service workers, and to be manipulated by the service workers.


[Web Authentication](https://w3c.github.io/webauthn/#api)
> user agents only expose this API to callers in secure contexts.



[Generic Sensor API](https://w3c.github.io/sensors/#secure-context)
> all interfaces defined by this specification or extension specifications are only available within a secure context.
