### ISSUE TITLE
Example is a little bit misleading still

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/web-share#62]
The example states "Share successful"... but that's not quite correct. What was successful there was just the handoff of the data, but not necessarily that the sharing actually happened.... I know, I'm nit picking a bit here, but we don't want to mislead people into thinking the API is doing more than it actually does.

**Comment by maxnordlund** [comment]
I do think it's good though, as the script shouldn't be able to tell the difference between a successful share and a failed one. This leaks information, and I can imagine an attack where you time the share dialog and targets a specific service to enumerate which apps are installed (or something like that).

**Comment by ewilligers** [comment]
@marcoscaceres do you have any suggested alternate wording? The WebShare API call reported success, the wording seems reasonable.

**Comment by marcoscaceres** [comment]
Maybe just "Data was shared successfully"?
