### ISSUE TITLE
Specify behavior when a file type is rejected

### ISSUE THREAD

**Issue by ewilligers** [WICG/web-share#90]
Some user agents may wish to prevent certain file types, for example executable files, from being shared. This decision might be made on the basis of MIME type or file extension, and the platform.

For example, Blink identifies various file extensions as dangerous:  [download_file_types](https://cs.chromium.org/chromium/src/chrome/browser/resources/safe_browsing/download_file_types.asciipb).

Some user agents may wish to prevent certain sites from sharing, for example known phishing sites.

Should script be able to detect in advance that such share attempts will fail? If so, then `share` should throw a `TypeError` and `canShare` should return `false`. If not, then `share` should throw a `NotAllowedError` (like if there was no user gesture) or `AbortError` (like if the user cancelled or there were no suitable share targets) and `canShare` should return `true`.

**Comment by raymeskhoury** [comment]
If the site can know beforehand whether it can share a file, it can provide better UX (e.g. not showing the share button in the first place). However fingerprinting may be a concern here.

**Comment by ewilligers** [comment]
`canShare` is synchronous, so its return result currently can't depend on any online service like [Google Safe Browsing](https://safebrowsing.google.com/). It hasn't shipped yet, so this can be changed if we would like sites to be able to detect which files can be shared.
